# untamed card llibrary

terms = {
    'animal': 'Animal - Card type. Animals can attack other Animals or the opponent’s Stronghold when they are Ready. Animals are placed on the table in the Exhausted position when played, and thus cannot attack on the turn they are played (unless they have SURGE).',
    'arrive': 'Arrive - Card Ability. This effect happens when an Animal comes into play. A player can also decide not to use the Arrive effect.',
    'fury': 'Fury - Token. A token that grants the Animal it is placed on +1 Attack for as long as the token remains on the Animal.',
    'guard': 'Guard - Card Ability. This Animal must first be defeated before other Animals or Strongholds can be attacked. When multiple Animals with Guard are on the board, the attacker may choose which one of them to attack. Guard does not affect Items and Animal/Stronghold card effects.',
    'item': 'Item - Card type. Items have a single use effect and are placed into their owner’s Stronghold after they are resolved.',
    'last words': 'Last Words - Card Ability. This effect happens when an Animal is defeated. A player can decide not to use the Last Words effect.',
    'power': 'Power - Resource. (<:cost:544901369518096384>) Any card that is placed face down in a player’s Power Area (on the left side of their Stronghold). Each card face down card in a player\'s Power Area counts as 1 Power. Players may only play a single card as a Power per turn and can have a maximum of 5 Power.',
    'rally': 'Rally - An indicator on a card. A player checks if the card(s) they draw when their Stronghold is defeated has the Rally indicator on it. If so, that card may immediately be played without having to pay the card’s Power Cost.',
    'reveal': 'Reveal - Card ability. When a card states to reveal a card, the player shows the card to the other player, then puts the card back where it came from. If multiple cards were revealed from the top of a player’s deck, put them back in the same order.',
    'surge': 'Surge - Card Ability. Animals with this ability come into play in the Ready Position and may immediately be used the turn it’s played to attack the opponents Animals. It cannot however attack the opponent’s Stronghold on the same turn it was played.',
    'support': 'Support - Resource. (:paw_prints:) A card that is discarded, an Animal that is defeated or an Item that has been used is placed in your Support Area (right side of your Stronghold). These can be used to pay for Support (:paw_prints:) abilities on cards. Cards that have been used to pay for Support costs are removed from the game afterwards.'}

credits = 'Game Design: Jeremy Falger, Milan Lefferts\n' \
        + 'Artists: Joe A. Howard, Andrew Soman, Julien Vandois, David Tenorio, Baukje Jagersma, Ilse Harting, Andrea Sodaro, Alex Shiga, Albert Bruun, Radu Mihai, Regis Torres\n' \
        + 'Product Manager: Vincent van Gils\n' \
        + 'Digital Support: Miltos Nedelkos\n' \
        + 'Playtesters: We would like to thank Max, Satrina, Pascal, bcsj, Jeroen, Marjolein, Ton, Cho, Niels, Tristan, Kenny, Andrew, Roland, René, Nicole, Tobiti, Jorad, Thomas, Tom, Elizzyble and all the others we might have forgotten.\n' \
        + 'Publisher: Grumpy Owl Games\n' \
        + 'Website: www.playuntamed.com, www.grumpyowlgames.com'

factions = {
    'rabbit': {
        'name': 'Rabbit',
        'discord_emoji': '<:untamedrabbit:544906418436964353>'}, #':rabbit:'},
    'panda': {
        'name': 'Panda',
        'discord_emoji': '<:untamedpanda:544906418394759179>'}, #':panda_face:'},
    'crocodile': {
        'name': 'Crocodile',
        'discord_emoji': '<:untamedcrocodile:544906418705399828>'}, #':crocodile:'},
    'fox': {
        'name': 'Fox',
        'discord_emoji': '<:untamedfox:544906418843680768>'}, #':fox:'},
    'rhino': {
        'name': 'Rhino',
        'discord_emoji': '<:untamedrhino:544906418671583233>'}, #':rhino:'},
    'chameleon': {
        'name': 'Chameleon',
        'discord_emoji': '<:untamedchameleon:544906418936086558>'}, #':frog:'},
	'rat': {
		'name': 'Rat',
		'discord_emoji': ':rat:'},
	'tiger': {
		'name': 'Tiger',
        'discord_emoji': ':tiger:'},
	'racoon': {
		'name': 'Racoon',
		'discord_emoji': ':bust_in_silhouette: '}}

cards = {
    'whitefur command': {
        'name': 'Whitefur Command',
        'type': 'stronghold',
        'rally': False,
        'faction': 'Rabbit',
        'cost': None,
        'power': None,
        'health': 7,
        'text': 'Pay 2 :paw_prints:: Deal 1 damage to an Animal OR Stronghold.',
        'img': None},
    'general greycoat': {
        'name': 'General Greycoat',
        'type': 'animal',
        'rally': False,
        'faction': 'Rabbit',
        'cost': 5,
        'power': 6,
        'health': 4,
        'text': 'ARRIVE: Choose one: Give another Animal 2 Fury OR Exhaust an Animal. You may pay 3 :paw_prints: to do both.',
        'img': None},
    'war council': {
        'name': 'War Council',
        'type': 'animal',
        'rally': False,
        'faction': 'Rabbit',
        'cost': 3,
        'power': 3,
        'health': 4,
        'text': 'ARRIVE: You may return a friendly Animal in play to your hand.\nLAST WORDS: Give an Animal 1 Fury.',
        'img': None},
    'whitefur infantry': {
        'name': 'Whitefur Infantry',
        'type': 'animal',
        'rally': True,
        'faction': 'Rabbit',
        'cost': 1,
        'power': 1,
        'health': 2,
        'text': 'ARRIVE: This gains SURGE OR this gains 1 Fury. You may pay 2 :paw_prints: to do both.',
        'img': None},
    'whitefur artillery': {
        'name': 'Whitefur Artillery',
        'type': 'animal',
        'rally': True,
        'faction': 'Rabbit',
        'cost': 2,
        'power': 2,
        'health': 3,
        'text': 'ARRIVE: Deal 1 Damage to an Animal OR to a Stronghold. You may pay 2 :paw_prints: to do both.',
        'img': None},
    'carrot saber': {
        'name': 'Carrot Saber',
        'type': 'item',
        'rally': False,
        'faction': 'Rabbit',
        'cost': 2,
        'power': None,
        'health': None,
        'text': 'Deal 2 Damage to an Animal. If defeats it, give an Animal SURGE.',
        'img': None},
    'blackstone vault': {
        'name': 'Blackstone Vault',
        'type': 'stronghold',
        'rally': False,
        'faction': 'Panda',
        'cost': None,
        'power': None,
        'health': 7,
        'text': 'Pay 3 :paw_prints:: Draw a card.',
        'img': None},
    'ursan gambler': {
        'name': 'Ursan Gambler',
        'type': 'animal',
        'rally': False,
        'faction': 'Panda',
        'cost': 1,
        'power': 1,
        'health': 2,
        'text': 'ARRIVE: Put the top 2 cards of your deck into your Support Area. If there was a Panda among them, this gains 2 Fury.',
        'img': None},
    'radann, merchant-king': {
        'name': 'Radann, Merchant-King',
        'type': 'animal',
        'rally': False,
        'faction': 'Panda',
        'cost': 5,
        'power': 4,
        'health': 6,
        'text': 'You may pay 5 :paw_prints: instead of paying this card\'s Power cost.\nLAST WORDS: Trigger your Stronghold ability for free. This does not count as a use of your Stronghold ability this turn.',
        'img': None},
    'blackstone broker': {
        'name': 'Blackstone Broker',
        'type': 'animal',
        'rally': True,
        'faction': 'Panda',
        'cost': 2,
        'power': 2,
        'health': 3,
        'text': 'Whenever you use your Stronghold ability, this gains 1 Fury.\nLAST WORDS: Put the top 2 cards of your deck into your Support Area.',
        'img': None},
    'oromancer': {
        'name': 'Oromancer',
        'type': 'animal',
        'rally': True,
        'faction': 'Panda',
        'cost': 5,
        'power': 4,
        'health': 6,
        'text': 'Whenever you use your Stronghold ability, deal 1 Damage to a Stronghold.\nGuard',
        'img': None},
    'blackstone treasury': {
        'name': 'Blackstone Treasury',
        'type': 'item',
        'rally': False,
        'faction': 'Panda',
        'cost': 4,
        'power': None,
        'health': None,
        'text': 'You may Pay 5 :paw_prints: instead of paying this card\'s Power Cost.\nDraw 2 cards. Exhaust an enemy Animal.',
        'img': None},
    'goldscale temple': {
        'name': 'Goldscale Temple',
        'type': 'Stronghold',
        'rally': False,
        'faction': 'Crocodile',
        'cost': None,
        'power': None,
        'health': 7,
        'text': 'Pay 3 :paw_prints:: Trigger the LAST WORDS ability of a friendly Animal in play or in your Support Area.',
        'img': None},
    'toothblade magus': {
        'name': 'Toothblade Magus',
        'type': 'animal',
        'rally': True,
        'faction': 'Crocodile',
        'cost': 2,
        'power': 2,
        'health': 2,
        'text': 'ARRIVE: You may pay 3 :paw_prints: to give this SURGE.\nLAST WORDS: Deal 2 Damage to a Stronghold.',
        'img': None},
    'high-priestess mekhet': {
        'name': 'High-Priestess Mekhet',
        'type': 'animal',
        'rally': False,
        'faction': 'Crocodile',
        'cost': 4,
        'power': 5,
        'health': 5,
        'text': 'ARRIVE: You may pay 2 :paw_prints: to Exhaust an Animal.\nLAST WORDS: Draw a card.',
        'img': None},
    'goldscale archer': {
        'name': 'Goldscale Archer',
        'type': 'animal',
        'rally': True,
        'faction': 'Crocodile',
        'cost': 1,
        'power': 1,
        'health': 1,
        'text': 'LAST WORDS: Deal 1 Damage to up to 2 Animals.',
        'img': None},
    'toothblade chosen': {
        'name': 'Toothblade Chosen',
        'type': 'animal',
        'rally': False,
        'faction': 'Crocodile',
        'cost': 4,
        'power': 3,
        'health': 5,
        'text': 'ARRIVE: For each Animal in your Support Area with LAST WORDS, this gains 1 Fury.\nGUARD.',
        'img': None},
    'goldscale amulet': {
        'name': 'Goldscale Amulet',
        'type': 'item',
        'rally': False,
        'faction': 'Crocodile',
        'cost': 1,
        'power': None,
        'health': None,
        'text': 'Remove a card from your Support Area from the game and trigger it\'s LAST WORDS ability. You may pay 3 :paw_prints: to repeat this with a second card in your Support Area.',
        'img': None},
    'spiritsong lodge': {
        'name': 'Spiritsong Lodge',
        'type': 'stronghold',
        'rally': False,
        'faction': 'Rhino',
        'cost': None,
        'power': None,
        'health': 7,
        'text': 'Pay 2 :paw_prints:: Give 1 Fury to an Animal.',
        'img': None},
    'rockhide berserker': {
        'name': 'Rockhide Berserker',
        'type': 'animal (rally)',
        'rally': True,
        'faction': 'Rhino',
        'cost': 2,
        'power': 1,
        'health': 4,
        'text': 'SURGE.\nFor each Fury this gains, deal 1 damage to a Stronghold.',
        'img': None},
    'wildcaller mo\'gara': {
        'name': 'Wildcaller Mo\'Gara',
        'type': 'animal',
        'rally': False,
        'faction': 'Rhino',
        'cost': 3,
        'power': 3,
        'health': 3,
        'text': 'ARRIVE: Move 1 damage from an Animal to another Animal. If this effect defeats the target, this gains 1 Fury. You may pay 2 :paw_prints: to move 2 damage instead.',
        'img': None},
    'rockhide defender': {
        'name': 'Rockhide Defender',
        'type': 'animal',
        'rally': True,
        'faction': 'Rhino',
        'cost': 3,
        'power': 2,
        'health': 4,
        'text': 'GUARD.\nEach time this takes damage, this gains 1 Fury.',
        'img': None},
    'the bonehammer': {
        'name': 'The Bonehammer',
        'type': 'item',
        'rally': False,
        'faction': 'Rhino',
        'cost': 4,
        'power': None,
        'health': None,
        'text': 'You may pay 5 :paw_prints: instead of paying this card\'s Power cost.\nDeal 2 damage to up to 2 Animals each.',
        'img': None},
    'war drums': {
        'name': 'War Drums',
        'type': 'item',
        'rally': False,
        'faction': 'Rhino',
        'cost': 1,
        'power': None,
        'health': None,
        'text': 'You may pay 2 :paw_prints: instead of paying this card\'s Power cost.\nAll Animals you play this turn comes into play with 1 Fury.',
        'img': None},
    'the black market': {
        'name': 'The Black Market',
        'type': 'stronghold',
        'rally': False,
        'faction': 'Fox',
        'cost': None,
        'power': None,
        'health': 7,
        'text': 'Pay 2 :paw_prints:: Reveal the top card of your deck. If it\'s an Animal, give an Animal -2 Atack until end of turn. If it\'s an Item, draw it.',
        'img': None},
    'spymaster rohana': {
        'name': 'Spymaster Rohana',
        'type': 'animal',
        'rally': False,
        'faction': 'Fox',
        'cost': 5,
        'power': 2,
        'health': 4,
        'text': 'ARRIVE: Reveal the top 2 cards of your deck. Deal damage to a Stronghold equal to the highest cost card revealed. Gain Fury equal to the lowest cost card revealed.',
        'img': None},
    'reinhard thief': {
        'name': 'Reinhard Theif',
        'type': 'animal',
        'rally': True,
        'faction': 'Fox',
        'cost': 1,
        'power': 2,
        'health': 1,
        'text': 'ARRIVE: You may pay 3 :paw_prints: to move all Fury from an Animal to this card.\nSURGE',
        'img': None},
    'scheming seer': {
        'name': 'Scheming Seer',
        'type': 'animal',
        'rally': True,
        'faction': 'Fox',
        'cost': 3,
        'power': 3,
        'health': 4,
        'text': 'ARRIVE: You may pay 2 :paw_prints: to give an Animal -2 Attack until end of turn.\nLAST WORDS: Put a card from your Support Area on top of your deck.',
        'img': None},
    'spyglass': {
        'name': 'Spyglass',
        'type': 'item',
        'rally': False,
        'faction': 'Fox',
        'cost': 1,
        'power': None,
        'health': None,
        'text': 'Reveal the top 2 cards of your deck, put them back on the top or the bottom of your deck in any order. For each Animal revealed, put 1 Fury on an Animal.',
        'img': None},
    'hidden blade': {
        'name': 'Hidden Blade',
        'type': 'item',
        'rally': False,
        'faction': 'Fox',
        'cost': 3,
        'power': None,
        'health': None,
        'text': 'Choose a friendly Animal. You may pay 4 :paw_prints: to give that Animal gains +2 Attack until end of turn. Deal damage equal to that Animal\'s Attack to another Animal.',
        'img': None},
    'the laboratory': {
        'name': 'The Laboratory',
        'type': 'stronghold',
        'rally': False,
        'faction': 'Chameleon',
        'cost': None,
        'power': None,
        'health': 7,
        'text': 'Pay 2 :paw_prints:: Replace 1 Damage on an Animal with 1 Fury.',
        'img': None},
    'dr. dolores': {
        'name': 'Dr. Dolores',
        'type': 'animal',
        'rally': False,
        'faction': 'Chameleon',
        'cost': 4,
        'power': 4,
        'health': 5,
        'text': 'ARRIVE: You may pay 4 :paw_prints: to play a card with cost 3 or less from your hand without paying it\'s Power cost.',
        'img': None},
    'shiftscale assassin': {
        'name': 'Shiftscale Assassin',
        'type': 'animal',
        'rally': True,
        'faction': 'Chameleon',
        'cost': 1,
        'power': 1,
        'health': 2,
        'text': 'ARRIVE: You may pay 1 :paw_prints: to Exhaust an Animal.\nThis has +1 Attack during your turn.',
        'img': None},
    'lab deceptionist': {
        'name': 'Lab Deceptionist',
        'type': 'animal',
        'rally': False,
        'faction': 'Chameleon',
        'cost': 2,
        'power': 2,
        'health': 2,
        'text': 'ARRIVE: You may pay 2 :paw_prints: to choose an Animal with Fury on it. This gains Fury equal to that of the chosen Animal.\nSURGE.',
        'img': None},
    'expert alchemist': {
        'name': '"Expert" Alchemist',
        'type': 'animal',
        'rally': True,
        'faction': 'Chameleon',
        'cost': 3,
        'power': 1,
        'health': 3,
        'text': 'ARRIVE: Choose an Animal. This gains Fury equal to that Animal\'s base Attack value.\nWhenever you play an Animal, you may move a Fury from this card to that Animal.',
        'img': None},
    'vile concoction': {
        'name': 'Vile Concoction',
        'type': 'item',
        'rally': False,
        'faction': 'Chameleon',
        'cost': 1,
        'power': None,
        'health': None,
        'text': 'Deal 1 damage to an Animal.\nYou may pay 2 :paw_prints: to also deal 2 damage to a different Animal.',
        'img': None},
	'the shipyard': {
		'name': 'The Shipyard',
		'type': 'stronghold',
        'rally': False,
		'faction': 'Rat',
		'cost': None,
		'power': None,
		'health': 7,
		'text': 'Pay 2 :paw_prints:: Place a card with Power cost 1 or less from your Support Area into your hand.',
		'img': None},
	'the rat king': {
		'name': 'The Rat "King"',
		'type': 'animal',
        'rally': False,
		'faction': 'Rat',
		'cost': 4,
		'power': 3,
		'health': 4,
		'text': 'Whenever another Animal is defeated, deal 1 damage to a Stronghold\nLAST WORDS: Return an Animal with Power cost 2 or less from your Support Area without paying its Power cost.',
		'img': None},
	'backalley bruiser': {
		'name': 'Backalley Bruiser',
		'type': 'animal',
        'rally': True,
		'faction': 'Rat',
		'cost': 3,
		'power': 3,
		'health': 3,
		'text': 'GUARD.\nWhenever this takes damage, your opponent must put 1 Fury on one of your Animals..',
		'img': None},
	'ratto enforcer': {
		'name': 'Ratto Enforcer',
		'type': 'animal',
        'rally': True,
		'faction': 'Rat',
		'cost': 2,
		'power': 1,
		'health': 2,
		'text': 'ARRIVE: This gains 2 Fury.\nLAST WORDS: Move all Fury on this to another Animal.',
		'img': None},
	'ratto thug': {
		'name': 'Ratto Thug',
		'type': 'animal',
        'rally': False,
		'faction': 'Rat',
		'cost': 1,
		'power': 2,
		'health': 1,
		'text': 'ARRIVE: You may pay 2 :paw_prints: to deal 1 damage to an Animal. If that Animal is defeated, draw a card.',
		'img': None},
	'explosive barrel': {
		'name': 'Explosive Barrel',
		'type': 'item',
        'rally': False,
		'faction': 'Rat',
		'cost': 2,
		'power': None,
		'health': None,
		'text': 'You may pay 3 :paw_prints: instead of paying this card\'s Power cost.\nYour opponent must deal 3 damage to Animals they control, divided as they wish.',
		'img': None},
	'the hunting grounds': {
		'name': 'The Hunting Grounds',
		'type': 'stronghold',
        'rally': False,
		'faction': 'Tiger',
		'cost': None,
		'power': None,
		'health': 7,
		'text': 'Pay 3 :paw_prints:: Deal 1 damage to an Animal. If this damage defeats that Animal, draw a card.',
		'img': None},
	'korinne the huntsman': {
		'name': 'Korinne the Huntsman',
		'type': 'animal',
        'rally': False,
		'faction': 'Tiger',
		'cost': 4,
		'power': 4,
		'health': 5,
		'text': 'SURGE.\nWhen this deals more damage to an Animal than that Animal\'s remaining Defense value, deal 2 damage to a Stronghold.',
		'img': None},
	'bonefang huntress': {
		'name': 'Bonefang Huntress',
		'type': 'animal',
        'rally': True,
		'faction': 'Tiger',
		'cost': 2,
		'power': 2,
		'health': 3,
		'text': 'ARRIVE: You may pay 2 :paw_prints: to deal 1 damage to an Animal. If that defeats it, this gains 1 Fury.\nLAST WORDS: Deal 1 damage to a Stronghold',
		'img': None},
	'jungle prowler': {
		'name': 'Jungle Prowler',
		'type': 'animal',
        'rally': True,
		'faction': 'Tiger',
		'cost': 2,
		'power': 3,
		'health': 2,
		'text': 'When this deals more damage to an Animal than that Animal\'s remaining Defense value, give an Animal 2 Fury.',
		'img': None},
	'trackers compass': {
		'name': 'Tracker\'s Compass',
		'type': 'item',
        'rally': False,
		'faction': 'Tiger',
		'cost': 1,
		'power': None,
		'health': None,
		'text': 'Look at the top 2 cards of your deck, draw one and put the other on the bottom of your deck.\nYou may pay 3 :paw_prints: to draw both cards instead.',
		'img': None},
	'heartpiercer arrow': {
		'name': 'Heartpiercer Arrow',
		'type': 'item',
        'rally': False,
		'faction': 'Tiger',
		'cost': 3,
		'power': None,
		'health': None,
		'text': 'Deal 2 damage to an Animal. If that Animal is defeated, you may deal 1 damage to up to 2 other Animals.',
		'img': None},
	'darkmask hold': {
		'name': 'Darkmask Hold',
		'type': 'stronghold',
        'rally': False,
		'faction': 'Racoon',
		'cost': None,
		'power': None,
		'health': 7,
		'text': 'Pay 3 :paw_prints:: Heal an Animal for 2 OR give an Animal +2 attack until the end of your turn.',
		'img': None},
	'professor noctus': {
		'name': 'Professor Noctus',
		'type': 'animal',
        'rally': False,
		'faction': 'Racoon',
		'cost': 4,
		'power': 3,
		'health': 5,
		'text': 'ARRIVE: Double the amount of Fury on an Animal.\nWhenever a friendly Animal gains Fury, deal 1 damage to a Stronghold.',
		'img': None},
	'selfless scientist': {
		'name': 'Selfless Scientist',
		'type': 'animal',
        'rally': True,
		'faction': 'Racoon',
		'cost': 1,
		'power': 0,
		'health': 2,
        'text': 'GUARD.\nLAST WORDS: Give a friendly Animal 2 Fury.',
		'img': None},
	'darkmask medic': {
		'name': 'Darkmask Medic',
		'type': 'animal',
        'rally': True,
		'faction': 'Racoon',
		'cost': 2,
		'power': 2,
		'health': 3,
		'text': 'ARRIVE: Heal an Animal or Stronghold for 2.',
		'img': None},
	'enforcer schematics': {
		'name': 'Enforcer Schematics',
		'type': 'item',
        'rally': False,
		'faction': 'Racoon',
		'cost': 1,
		'power': None,
		'health': None,
		'text': 'Give an Animal +2 Attack until end of your turn.\nYou may pay 3 :paw_prints: to have that Animal also not take damage when attacking this turn.',
		'img': None},
	'lightning rod': {
		'name': 'Lightning Rod',
		'type': 'item',
        'rally': False,
		'faction': 'Racoon',
		'cost': 2,
		'power': None,
		'health': None,
		'text': 'Give 1 Fury to up to 2 friendly Animals.\nYou may pay 4 :paw_prints: to Exhaust up to 2 enemy Animals.',
		'img': None}}
        
